import { truncAddr } from "@/lib/format";

type IdentityUser = {
  username?: string | null;
  ensName?: string | null;
  ens_name?: string | null;
  baseName?: string | null;
  base_name?: string | null;
  activeIdentity?: string | null;
  active_identity?: string | null;
  walletAddress?: string | null;
  wallet_address?: string | null;
};

export function getDisplayName(user: IdentityUser): string {
  const identity = user.activeIdentity || user.active_identity || "username";
  const ensName = user.ensName || user.ens_name;
  const baseName = user.baseName || user.base_name;
  const username = user.username;
  const wallet = user.walletAddress || user.wallet_address || "";

  // Respect explicit identity preference
  if (identity === "ens" && ensName) return ensName;
  if (identity === "base" && baseName) return baseName;

  // For "username" identity: if it's auto-generated (human-*) and we have
  // a resolved ENS/Base name, prefer that over the placeholder username
  if (identity === "username") {
    const isAutoGenerated = username && /^human-[a-z0-9]+$/.test(username);
    if (!isAutoGenerated && username) return username;
    if (ensName) return ensName;
    if (baseName) return baseName;
    if (username) return username;
  }

  // Fallback chain: ENS → Base → username → truncated wallet
  return ensName || baseName || username || truncAddr(wallet);
}

export function getAvatarUrl(user: IdentityUser & {
  avatarUrl?: string | null;
  avatar_url?: string | null;
  ensAvatar?: string | null;
  ens_avatar?: string | null;
  baseAvatar?: string | null;
  base_avatar?: string | null;
}): string | null {
  const identity = user.activeIdentity || user.active_identity || "username";
  const ensAvatar = user.ensAvatar || user.ens_avatar;
  const baseAvatar = user.baseAvatar || user.base_avatar;
  const avatarUrl = user.avatarUrl || user.avatar_url;

  if (identity === "ens" && ensAvatar) return ensAvatar;
  if (identity === "base" && baseAvatar) return baseAvatar;

  return avatarUrl || ensAvatar || baseAvatar || null;
}

export function getInitials(user: IdentityUser): string {
  const name = getDisplayName(user);
  const wallet = user.walletAddress || user.wallet_address || "";

  // If the display name is a truncated address, use wallet chars
  if (name.includes("...") && wallet) {
    return wallet.slice(2, 4).toUpperCase();
  }

  return name.charAt(0).toUpperCase();
}
